### PR TITLE
Add additional wildcard entities

### LINKED ISSUE #59: Make pybids_inputs more permissive
## The problem

SCATTR currently fails on inputs datasets that have some "extra" entities like `acq` or `run` -- it would be nice to support them by adding them as wildcards to `pybids_inputs` in the config.

### PR DESCRIPTION
**Pull request by kaitj**
## Proposed changes

Resolves #59. Adds additional wildcard entities - namely acquisition and run. Also added in direction for diffusion data. Are there any others that should be added?

Also reverts a change to correct for the singularity container uris.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [x] Changes have been tested to ensure that fix is effective or that a feature works.
- [x] Changes pass the unit tests
- [x] Code has been run through the `poe quality` task
- [x] I have included necessary documentation or comments (as necessary)
- [x] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

### CODE REVIEW

**Comment by tkkuehn** [comment]
> Are there any others that should be added?

Looking through the spec, the following could be options:

For `T1w`:
- `ce` (Not sure if SCATTR would handle contrast-enhanced images)
- `rec` (I think we may as well include this as a wildcard, I don't think we care)
- `part` (I need to look into whether snakebids allows you to specify something like "if `part` is defined, we only want `mag`)

For `dwi`: `rec` and `part` (see above)

For `mask`:
- `space`
  - Slight rabbit hole here... The [section about masks](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#masks) says this should be `orig` if there hasn't been a transformation. The [definition of the `space` entitity](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#space) says this must come from one of the modality specific lists in [this appendix](https://bids-specification.readthedocs.io/en/stable/appendices/coordinate-systems.html#image-based-coordinate-systems). The appendix says that images not registered to a template can be either `individual`, `study`, or `scanner` (default, but `space` should just be omitted in this case). The [spatial references section](https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html#spatial-references) sees to support the definition of the `space` entity.
  - Ultimately I guess this should be excluded or filtered to something like `[orig, scanner, individual]`?
- `res` (I think this should be a wildcard)
- `den` (I don't really understand why this applies to image masks)

**Comment by kaitj** [comment]
## T1w

- In theory it could handle contrast-enhanced, but in practice the registration would likely fail. I'd leave this out for (unless we end up incorporating something to remove the contrast enhancement
- Agree about `rec` and `part` (also for diffusion)

## Mask

- I think we can leave out `den` (as this would be more relevant for surface processing, which we don't do here)
- `label` again I think we can leave out, given these are whole brain masks as you noted
- Agree about `res`
- `space` gets tricky as i feel like this isn't really followed. I think we can include this with the filters you suggested, but also include `T1w` (selfishly, this is used in a lot of the datasets that we are using, and what we are expecting currently).

**Comment by tkkuehn** [comment]
Sounds good on all counts -- will approve once you've made those changes.

**Comment by kaitj** [comment]
Added in the additional entities, with the caveat that `part` is causing the workflow to fail as it expected the entity to exist if it is included in `filters`

**Review by tkkuehn — APPROVED** [review]

**Comment by kaitj** [comment]
Will merge this in, and fix the `part` wildcard / filtering in a separate PR.

**Pull request merged**
